apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-secret-creator-sa
  namespace: open-cluster-management-observability
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-storage-secret-creator
  namespace: open-cluster-management-observability
subjects:
  - kind: ServiceAccount
    name: thanos-secret-creator-sa
    namespace: open-cluster-management-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-storage-secret-creator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-storage-secret-creator
  namespace: open-cluster-management-observability
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get","create","patch","update"]
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs:     ["get","create","patch","update"]
