apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-operators-redhat
spec: {}
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-logging
spec: {}
