apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-secret-creator-sa
  namespace: openshift-logging
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loki-storage-secret-creator
  namespace: openshift-logging
subjects:
  - kind: ServiceAccount
    name: loki-secret-creator-sa
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-storage-secret-creator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loki-storage-secret-creator
  namespace: openshift-logging
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get","create","patch","update"]
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs:     ["get","create","patch","update"]
