apiVersion: batch/v1
kind: Job
metadata:
  name: loki-storage-secret-cronjob
  namespace: openshift-logging
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 60
  backofflimit: 5
  template:
    metadata:
      name: loki-storage-secret-cronjob
    spec:
      containers:
      - name: loki-storage-secret-provisioner
        image: registry.redhat.io/openshift4/ose-cli:v4.11
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - |
          export BUCKETNAME=`oc get obc logs-bucket -n openshift-logging -o jsonpath={.spec.bucketName}`
          export AWS_ACCESS_KEY_ID=`oc get secret logs-bucket -n openshift-logging -o go-template='{{.data.AWS_ACCESS_KEY_ID|base64decode}}'`
          export AWS_SECRET_ACCESS_KEY=`oc get secret logs-bucket -n openshift-logging -o go-template='{{.data.AWS_SECRET_ACCESS_KEY|base64decode}}'`

          cat <<EOF | oc apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: logging-loki-s3
            namespace: openshift-logging
          type: Opaque
          stringData:
            access_key_id: $AWS_ACCESS_KEY_ID
            access_key_secret: $AWS_SECRET_ACCESS_KEY
            bucketnames: $BUCKETNAME
            endpoint: s3.openshift-storage.svc:443
            #region: eu-central-1
          EOF
      restartPolicy: OnFailure
      serviceAccountName: loki-secret-creator-sa
