apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: o11y
spec:
  datasources:
    - access: proxy
      editable: true
      jsonData:
        httpHeaderName1: X-Scope-OrgID
        timeInterval: 5s
        tlsSkipVerify: true
      name: Loki
      secureJsonData:
        httpHeaderValue1: application
      type: loki
      url: >-
        https://logging-loki-query-frontend-http.openshift-logging.svc.cluster.local:3100
    - access: proxy
      editable: true
      jsonData:
        httpHeaderName1: X-Scope-OrgID
        timeInterval: 5s
        tlsSkipVerify: true
      name: Loki (Audit)
      secureJsonData:
        httpHeaderValue1: audit
      type: loki
      url: >-
        https://logging-loki-query-frontend-http.openshift-logging.svc.cluster.local:3100
    - access: proxy
      editable: true
      jsonData:
        httpHeaderName1: X-Scope-OrgID
        timeInterval: 5s
        tlsSkipVerify: true
      name: Loki (Infrastructure)
      secureJsonData:
        httpHeaderValue1: infrastructure
      type: loki
      url: >-
        https://logging-loki-query-frontend-http.openshift-logging.svc.cluster.local:3100
  name: loki-datasource.yaml
